dojot/flowbroker

orchestrator/node-red/src/tinker/nodes.html, orchestrator/nodes/geo/geo.html
This is related to dojot/dojot#284
=> Fixes geo region selections

orchestrator/node-red/src/tinker/nodes.html, orchestrator/nodes/geo/geo.html
This is connected to dojot/dojot#284
=> Fixes geo drawing on chrome

orchestrator/node-red/src/tinker/nodes.html, orchestrator/nodes/geo/geo.html
This is connected to dojot/dojot#345
=> Fixes parsing of configured data, removes bogus toolbar item

orchestrator/amqp.js, orchestrator/executor.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/kafka.js, orchestrator/nodes/change/index.js, orchestrator/nodes/device-out/device-out.js, orchestrator/nodes/switch/index.js, orchestrator/nodes/template/index.js, orchestrator/publisher.js
This is connected to dojot/dojot#326
=> Improves initialization of the service

.travis.yml, travis/deploy-gh-pages.sh
This is connected to dojot/dojot#282
=> Adding ghpages deploy

orchestrator/dispatcher.js, orchestrator/nodeManager.js
This is connected to dojot/dojot#373
=> Fixes deployment of unknown images

orchestrator/nodes/email/email.html
This is connected to dojot/dojot#370
=> Fixes email configuration rendering

orchestrator/nodes/template-in/template-in.html
This is connected to dojot/dojot#371
=> Fixes template selection memoization

orchestrator/flowManager.js, orchestrator/ingestor.js, orchestrator/nodes/template-in/template-in.html
This is connected to dojot/dojot#382
=> Flowbroker fixes

orchestrator/nodes/device-in/device-in.html, orchestrator/nodes/device-out/device-out.html, orchestrator/nodes/template-in/template-in.html
This is connected to dojot/dojot#391
=> Fixes device/template selection selection boxes

orchestrator/nodes/email/email.html, orchestrator/nodes/email/index.js, orchestrator/package-lock.json, orchestrator/package.json
For some reason, email's node handler implementation was commented.
This does the uncommenting, and fixes a number of issues for that node.
=> Fixes email node

orchestrator/nodes/http/http.html, orchestrator/nodes/http/index.js, orchestrator/package-lock.json, orchestrator/package.json
This is connected to dojot/docker-compose#55
=> Uncomments http node

orchestrator/flowManager.js, orchestrator/nodeManager.js
This fixes dojot/dojot#489 and #43 
Kudos to @fberanizo for finding this out!
=> Fix single remote node

orchestrator/nodeManager.js
This is connected to dojot/dojot#560
=> Fixing docker support

travis/publish.sh
This is child of dojot/dojot#563
=> ci: fix travis publish.sh script.

lib/CommandHandler.js, orchestrator/executor.js, orchestrator/nodes/actuate/actuate.js, orchestrator/nodes/device-out/device-out.js, orchestrator/nodes/remoteNode/index.js
- Adds metadata to the handleMessage on function nodes, now
it is possible to retrieve the flowId, tenant and originatorDeviceId
by this new parameter.
This is connected to dojot/dojot#585
=> Adds metadata to the handleMessage on function nodes

orchestrator/nodes/geo/index.js
Code refactoring.
N/A
N/A
No.
Not that I'm aware of.
Code refactoring just for the sake of readability, thereafter maintainability.
=> Refactor method handleMessage of geo DataHandler class

travis/publish.sh
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
Push context-manager image to dockerhub
It is not pushed, therefore breaking docker-compose (or any other orchestration mechanism)
Travis will push context-manager image to docker hub
No
* **Is there any issue related to this PR in other repository?** …
=> ci: push context-manager image to docker hub

orchestrator/nodes/actuate/actuate.html, orchestrator/nodes/actuate/actuate.js, orchestrator/nodes/device-out/device-out.html, orchestrator/nodes/device-out/device-out.js
Feature: new configuration to Actuate node
The actuate node allows only to actuate on a node defined on configuration time
Adds configuration to actuate on a node defined on runtime.
Adds configuration to actuate on a node which has been triggered the flow.
Obs: The previous behavior is supported yet
Yes, flows that use this node will be affected and will need to be reconfigured.
* **Is …
=> Adds more configuration on output nodes

.github/CODEOWNERS
git management
there is no default reviewer
This commit adds the @dojot/developers as default reviewer for this repository
No
No
=> Adds CODEOWNERS to the repository

.dockerignore, orchestrator/auth.js, orchestrator/config.js, orchestrator/flowManager.js, orchestrator/ingestor.js, orchestrator/kafka.js
This PR introduces bug fixes and feature.
Currently, iotagent that has to do requests to device-manager, which is, problably, delivering messed up messages to kafka. 
The new behavior is that, now, flowbroker calls  device-manager to get the list of templates of a device when a message is received from this device.
No.
* **Is there any issue related to this PR in other repository?** …
=> Flowbroker requests list of templates to device-manager

orchestrator/nodes/actuate/actuate.html, orchestrator/nodes/device-out/device-out.html
Bug fix
This is connected to dojot/dojot#668
Not
Yes, dojot/dojot#668
=> Fix output nodes

orchestrator/nodeManager.js, orchestrator/nodes/get-context/get-context.html, orchestrator/nodes/get-context/get-context.js, orchestrator/package.json
Feature
No
No
This new node gives the possibility to retrieve a context in the application layer. It supports retrieve tenant and flow contexts.
=> Adds a new node 'get context'

orchestrator/amqp.js, orchestrator/executor.js, orchestrator/index.js, orchestrator/ingestor.js
Enhancement 
Actually, there is no priority on the rabbitMQ's queues what allows newcomers events jump the queue and being processed before some older event.
This PR introduces the use of RabbitMQ priority queue. The reason is to avoid the situation explained previously. The idea is the use of a queue with two priorities, that will work as follows:
- Events from a newcomers flow event are added into the queue with minimum priority.
- Events from a flow that is being processed are added with maximum priority
* …
=> Changes the way that the flow's event are processed

orchestrator/config.js, orchestrator/nodes/dockerComposeRemoteNode/index.js
Bug fix.
Flowbroker couldn't find the correct network if there were two or more networks containing 'flowbroker' in their names.
The network name has to be defined by the user and, being each one unique, there won't be any problems in finding the correct one.
No.
This is connected to dojot/dojot#665.
* …
=> fix: fixes error when there are conflicting network names

orchestrator/ingestor.js
BugFix
This is connected to dojot/dojot#682
No
This is connected to dojot/dojot#682
=> Fixes the treatment of a flow event triggered by a template

orchestrator/ingestor.js, orchestrator/redisClientWrapper.js
Feature.
Static attributes can't be accessed on flows.
Now, static attributes can be used on flows.
No.
This is connected to dojot/dojot#679
=> Adds static attrs to payload then it can be used on flows

orchestrator/nodes/switch/index.js
Bug fix.
The switch node is not handling 'is null' and 'is not null'.
Switch node handles 'is null' and 'is not null' rules.
No.
No.
=> Fixed the handler of switch node to 'is null' and 'is not null' rules

orchestrator/nodes/actuate/actuate.html, orchestrator/nodes/device-in/device-in.html, orchestrator/nodes/device-out/device-out.html, orchestrator/nodes/template-in/template-in.html, orchestrator/nodes/template/template.html
Improvements
Flow: 
- template node, properties "flow" and "global" have no function
- template list is unordered
- device list is unordered
Improvements
No
This PR is connected to dojot/dojot#551.
This PR is connected to dojot/dojot#466.
This PR is connected to dojot/dojot#465.
* **Other …
=> Flow - Enhancement

orchestrator/amqp.js, orchestrator/config.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/nodeManager.js, orchestrator/package.json
Bug fix.
Messages might be handled out of order.
Messages are handled in order.
Solution: Messages are moved from the Kafka 'device-data' subject
to the queue 'event_queue' in Rabbitmq. Then they are pre-processed
one at a time and tasks are pushed to queue 'task_queue' to be processed
also one at a time. Once a task is processed if new tasks are spawned,
they have higher priorities.
It …
=> Changed the flowbroker to guarantee the events are processed in order

contextManager/ZookeeperHelper.js, contextManager/ZookeeperRWLock.js, contextManager/index.js, lib/ContextHandler.js, lib/ContextManagerClient.js, lib/package.json
Feature
The current algorithm to allow the exclusive access to a context is a simple lock
Changes to uses a rwlock implementation
Yes
No
- Adapts the lib to deal with the modification on contextManager
- Adds new methods on lib to just unlock the context and lock get and unlock …
=> Replaces the lock implementation by rwlock

orchestrator/api.js, orchestrator/package.json
Feature
Today, doesn't have a healthCheck endpoint to check a status from service.
This PR introduce a endpoint 'healthCheck' to check a status from service.
No.
No.
=> Healthcheck

contextManager.docker, contextManager/package-lock.json, orchestrator.docker
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR changes the base image for both Flowbroker and Flowbroker Context Manager to a more "stable" one (one that should not be updated anytime soon). Also, both Dockerfiles were updated so that the image size for both components were reduced, with no observable impact on functionality.
Current base image is `node:8` which was recently updated from Debian Jessie to Debian stretch. This caused a few other dojot components to break. In …
=> ci: checking image build, reducing docker size

.travis.yml, tests/docker-compose.yml, travis/publish.sh
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR adds a check when running jobs in Travis. Without it, PR could update the image tagged `latest` in DockerHub. Also, it changes a bit the internal images generated for testing (which are pushed afterwards to Docker Hub) so that they are properly tagged.
There is a chance that simply creating a pull-request could trigger a deploy to Docker Hub.
The type of build is …
=> ci: fixing docker image generation

orchestrator/nodes/get-context/get-context.js, orchestrator/package.json
Update dependencies
Uses an old version of lib @dojot/flow-node
Uses the current version of lib @dojot/flow-node
No
=> Updates the orchestrator to use the version 3.0.0-alpha1 of @dojot/flow-node

orchestrator/nodeManager.js
This PR introduce a Bug FIx
Currently, the remote node persisting is not working very well, because when the flowbroker was restart, the connections with remote node was lost.
This PR introduce a fix to that feature, and improve the collections map with mongoDB. 
No
This PR is connected to …
=> Fixing remote node

docs/api.apib, orchestrator/dispatcher.js, orchestrator/executor.js, orchestrator/nodeManager.js, orchestrator/nodes/actuate/actuate.js, orchestrator/nodes/change/index.js, orchestrator/nodes/device-out/device-out.js, orchestrator/nodes/dockerComposeRemoteNode/index.js, orchestrator/nodes/edge/index.js, orchestrator/nodes/email/index.js, orchestrator/nodes/geo/index.js, orchestrator/nodes/get-context/get-context.js, orchestrator/nodes/http/http.html, orchestrator/nodes/http/index.js, orchestrator/nodes/kubernetesRemoteNode/index.js, orchestrator/nodes/remoteNode/index.js, orchestrator/nodes/switch/index.js, orchestrator/nodes/template/index.js, orchestrator/package.json
Dependency update
The current implementation uses the lib @dojot/flow-node 3.0.0-alpha1
This PR updates the implementation to uses the lib @dojot/flow-node 3.0.0-alpha2, it means that:
- the dispatcher was changed to work in an asynchronous way
- all nodes implementations now use promises
No
* **Other …
=> Adapts the orchestrator to work with the lib modifications

orchestrator/nodes/template/index.js
bug fix
the node output does not work properly with the user selection
the node formats the output as required by the user
No
=> Fixes template node's output

orchestrator/nodes/dockerComposeRemoteNode/index.js
Enhancement
The remote node's container name is 'flowbroker.<random id>'
The remote node's container name is 'flowbroker.<tenant><node id>.<random id>'
=> Modifies remote nodes' container name format

orchestrator/api.js
Bug fix
the mandatory parameters are not checked in the create node endpoint
Now the parameters are checked
=> Adds parameter check in the "/v1/node" endpoint

orchestrator/nodes/template/index.js, orchestrator/nodes/template/locales/en-US/template.json, orchestrator/nodes/template/template.html, orchestrator/package.json
feature
The template node uses mustache as template engine
The template node uses handlebars as template engine
=> Replaces the template engine used on template node by handlebars

orchestrator/nodes/template/locales/en-US/template.json, orchestrator/nodes/template/template.html
Cleanup
Actually, the syntax highlight does not work and we do not have plans to give support to it
This option is not more available to the user. 
No
=> Removes the syntax highlight option from template node

orchestrator/nodes/device-out/device-out.html, orchestrator/nodes/device-out/device-out.js
feature
device out node accepts only one device
device out node accepts multiple devices
Yes, all flows with a device out configuration will be affected
- Modifies device out node's configuration to store only devices ids
instead label and device ids
=> Modifies device out node to accept multiple devices

contextManager.docker, orchestrator.docker, orchestrator/index.js
Sync to resolve bugfixes, to more details check the related issues/PR
No
dojot/flowbroker#119
dojot/flowbroker#120
Just sync the development branch with the master
=> Merges the master into development branch

orchestrator/ingestor.js
Bug fix
This PR is connected to dojot/dojot#977.
=> Notification - missing change config

orchestrator/api.js, orchestrator/ingestor.js, orchestrator/nodeManager.js, orchestrator/nodes/dockerComposeRemoteNode/index.js
Refactoring.
The node handler logic is not clear and there are some bugs.
The behavior is the same.
No.
It is related to:
- dojot/flowbroker#103
- dojot/flowbroker#104
- dojot/flowbroker#105
- dojot/dojot#904
=> Refactored node manager

orchestrator/nodeManager.js
- [NA ] Tests for the changes have been added (for bug fixes / features)
- [ NA] Docs have been added / updated (for bug fixes / features)
Removes a non-working feature
The email node is not working properly.
The email node is being removed for now, but it will be reinserted as soon as we fix it.
Removal of email node from flowbroker.
* **Is there any issue related to this PR in other …
=> Removed e-mail node for now

orchestrator/api.js, orchestrator/config.js, orchestrator/healthcheck.js, orchestrator/index.js, orchestrator/package-lock.json, orchestrator/package.json
Feature
The health-checking implemented for flowbroker is not useful because it doesn't monitor external services such as kafka and mongodb.
It monitors:
- connection with kafka
- connection with mongodb
- uptime
- cpu utilization
- memory utilization
No
No
=> Refactored the health ckecking mechanism for the flowbroker

orchestrator/nodeManager.js, orchestrator/nodes/device-out/device-out.html, orchestrator/nodes/device-out/device-out.js, orchestrator/nodes/device-out/locales/en-US.json, orchestrator/nodes/device-out/locales/pt-BR.json, orchestrator/nodes/multi-device-out/locales/en-US.json, orchestrator/nodes/multi-device-out/locales/pt-BR.json, orchestrator/nodes/multi-device-out/multi-device-out.html, orchestrator/nodes/multi-device-out/multi-device-out.js
Revert change to maintain retro compatibility
No
dojot/flowbroker#130
- Reverts the node 'device out' implementation to the previous (without support multiple devices)
- Adds a new node 'multi device out'
=> Reverts the node 'device out' implementation and add a new node 'multi device out'

orchestrator/nodeManager.js
Accepts some changes requested.
=> Added some fixes

orchestrator/nodeManager.js
A previous merge operation improperly removed the
notification node.
Bugfix.
The notification node was improperly removed.
The notification node was added again.
No.
No.
=> Fixed an improper merge conflict resolution

orchestrator/api.js, orchestrator/nodeManager.js
Import and export remote nodes
You can't import and export remote nodes
You have remote nodes in export json and can import it back
No
This PR is connected to dojot/dojot#1027
There is another related pull request in data-manager for this issue.
=> import and export remote nodes

orchestrator/nodes/switch/locales/pt-BR.json
=> fix: Correct the text in switch node

orchestrator/nodes/notification/index.js, orchestrator/nodes/notification/notification.html
Fix
The node notification has an output that does not make sense
This output has been removed
It also removes an unnecessary parameter from the node 'notification' class
=> Removes the node 'notification' output

orchestrator/nodes/template/index.js, orchestrator/nodes/template/template.html
feature
See #131 for more details
=> Merges feature template node stringify

orchestrator/nodeManager.js
Enable feature
It just enables the 'multi device out' node
=> Enables 'multi device out' node

orchestrator/index.js
Workaround to bugged code.
Third-party libraries may be bugged, and they might not handle
promises and exception properly. 
It was added a handler to kill flowbroker when unhandledRejection or uncaughtException happens.
No
It is related to dojot/dojot#1098, but it is not a fix for this issue.
* **Other …
=> It forces flowbroker dies when certain error events happen

orchestrator/nodes/device-out/device-out.js
bugfix
the node 'device-out' does not add the timestamp on metadata
dojot/dojot#1095
=> Adds timestamp on metadata when publishing a data using the device-out node

orchestrator/nodes/actuate/actuate.js, orchestrator/nodes/multi-actuate/multi_actuate.js
feature
the nodes related to actuate does not add the timestamp in the meta
the nodes related to actuate add the timestamp in the meta
No
dojot/dojot#1105
Adds the timestamp in the meta property for all actuate kafka messages
=> Adds timestamp to the actuate messages

orchestrator/nodeManager.js
remove log messages
Every time a node is requested to be displayed on GUI the flowbroker logs all the node's HTML code and JSON configuration
dojot/dojot#1133
just for performance issues
=> Removes some over detailed logs

orchestrator/ingestor.js
bug fix
There are some error flow without the adequate return
No
No
- Adds some missing returns
- Adds some error messages
- Changes some logger message level
=> Adds some missing returns

orchestrator/config.js, orchestrator/executor.js
feature
there is no timeout to the node execution
the node execution have a timeout configurable by the environment variable TASK_TIMEOUT
No
dojot/dojot#1137
The default timeout is 30 seconds
=> Adds timeout to the node execution

orchestrator/nodeManager.js, orchestrator/nodes/cumulative-sum/cumulative-sum.html, orchestrator/nodes/cumulative-sum/cumulative-sum.js, orchestrator/nodes/cumulative-sum/locales/en-US.json, orchestrator/nodes/cumulative-sum/locales/pt-BR.json
feature
Adds a new node the cumulative sum, it sums an attribute value in a temporal window
No
=> Adds a new node: cumulative sum

orchestrator/nodeManager.js, orchestrator/nodes/merge-data/locales/en-US.json, orchestrator/nodes/merge-data/locales/pt-BR.json, orchestrator/nodes/merge-data/merge-data.html, orchestrator/nodes/merge-data/merge-data.js
feature
Adds a new node, the merge data. This node allows objects to be merged.
No
=> Adds a new node: merge data

orchestrator/nodes/cumulative-sum/cumulative-sum.js, orchestrator/nodes/merge-data/merge-data.js
Bug fix
Parameter validation for the new processing nodes 'merge data' and 'cumulative sum' has bugs. 
Fixed the bug.
No
No
=> Fixed parameter validation for new processing nodes

lib/ContextManagerClient.js, lib/DojotHandler.js, lib/package-lock.json, lib/package.json
feature
There was no logging system, just the console.log
Adds the dojot-module-logger
No
- Adds the dojot-module-logger as the lib's logger system
- Updates the lib version
- Adds the package-lock file
=> Adds the dojot-module-logger as the lib's logger system

contextManager/ZookeeperHelper.js, contextManager/ZookeeperRWLock.js, contextManager/index.js, contextManager/package-lock.json, contextManager/package.json
feature
There was no logging system, just console.log
Adds the dojot-module-logger
No
=> Adds the dojot-module-logger as the context-manager's logger system

orchestrator/nodes/geo/geo.html, orchestrator/nodes/geo/index.js, orchestrator/nodes/geo/locales/en-US.json, orchestrator/nodes/geo/locales/pt-BR.json
Bug fix
Geo node isn't working with new input nodes due to the hardcoded path in the geo node
Adds a new configuration on the geo node, the `geopoint`, the user needs to fill this new configuration with the target attribute that contains the geo point.
Yes, all geo nodes previously configured become invalid due to the new configuration.
* **Is there any issue related to this PR in other …
=> fix: geofence node error

contextManager/index.js
Change logger port for context manager
The logger port is 80
The logger port can be provided through environment variable
No
Yes, this issue is connected to dojot/dojot#1178
=> environment variable for the logger port

orchestrator/amqp.js, orchestrator/executor.js, orchestrator/ingestor.js
Bugfix
There is no guarantee that the messages sent to rabbit MQ were been delivered
This PR changes the behavior to use the delivery mode with confirmation 
No
- Changes the rabbitMQ usage from callback to promise
=> Changes the implementation to confirm the publications on rabbit

orchestrator/executor.js
enhancement
Adds the node's id into the executor's log
No
No
=> Improves log messages

orchestrator/nodes/kubernetesRemoteNode/index.js
Bug fix kubernetes remote node
Remote node in k8s doens't work
Remote node in k8s can be deployed
No
Yes, this PR is connected to dojot/dojot#1261
=> bugfix remote node k8s

contextManager/index.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Release v0.4.1

orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
Bugfix starting flowbroker error with remote node
When flowbroker start, it tries to delete remote node deployment and create a new one
When flowbroker start, it does not try do delete deployment and try to create a new one if it does not exists
No
Yes, this PR is connected to dojot/dojot#1348
* …
=> fix: bugfix remote node on kubernetes

orchestrator/nodes/cron-batch/cron-batch.html, orchestrator/nodes/cron-batch/cron-batch.js, orchestrator/nodes/cron-batch/locales/en-US.json, orchestrator/nodes/cron-batch/locales/pt-BR.json
feature
the cron-batch timeout is hardcoded
the cron-batch timeout become configurable
No
=> Externs request timeout to cron-batch node

orchestrator/nodes/notification/index.js
Not valide types 
valide types 
dojot/dojot#1421
dojot/dojot#1299
=> fix: notification list crashes if the notification node configuration is incorrect

orchestrator/nodes/ftp/ftp.html, orchestrator/nodes/ftp/index.js
=> fix: FTP node, remove get

lib/ContextHandler.js, lib/ContextManagerClient.js, lib/DojotHandler.js, lib/package-lock.json, lib/package.json, tests/docker-compose.yml
improvements
No
Add more validations and improves code related to logging
pumps lib version
=> chore: Adds some improvements to lib

orchestrator/config.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/nodeManager.js, orchestrator/nodes/publish-ftp/index.js, orchestrator/nodes/publish-ftp/locales/en-US.json, orchestrator/nodes/publish-ftp/locales/pt-BR.json, orchestrator/nodes/publish-ftp/publish-ftp.html
feature
A new node to publish in ftp topic.
Ftp topic is {tenant}.dojot.ftp
dojot/dojot#1401
=> feat: new node to Publish in FTP topic

contextManager/index.js
improvement and fix
- simplifies error checking
- fixes exception handling
no
=> [ContextManager] Improves error checking

contextManager/index.js
=> [ContextMngr] Fixes reject call without object associated

contextManager/index.js
fix
the application kill itself correctly
no
=> [ContextMngr] Fixes how the process kill itself

orchestrator.docker, orchestrator/config.js, orchestrator/index.js
enhancement
the number of workers is configurable via application parameters
the number of workers is configurable via environment variable
No
=> Replaces the workers' configuration to env variable

orchestrator/config.js, orchestrator/index.js, orchestrator/ingestor.js
enhancement
not possible to configure kafka parameters
possible to configure kafka parameters
no
no
Adds the possibility to configure the kafka parameters via
environment variables. These variable should have the prefixes:
'kafka_consumer_' or 'kafka_producer_'
please check the …
=> Adds the possibility to configure kafka parameters

contextManager/index.js
=> [ContextMngr] Improves log

orchestrator/nodes/ftp/ftp.html, orchestrator/nodes/ftp/index.js
=> remove ftp get

orchestrator/nodes/multi-actuate/locales/pt-BR.json, orchestrator/nodes/multi-device-out/locales/pt-BR.json
=> Fixes label in portuguese

orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Change the parameter to remove node correctly

lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/package.json, lib/samples/kelvin/src/index.js
=> chore: upgrade libs examples [master]

orchestrator.docker, orchestrator/amqp.js, orchestrator/config.js, orchestrator/executor.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/util.js
=> feat: Changed to process messages in parallel [dev]

orchestrator.docker, orchestrator/amqp.js, orchestrator/config.js, orchestrator/executor.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/util.js
=> feat: Changed to process messages in parallel  [release/v0.5.0]

orchestrator.docker, orchestrator/amqp.js, orchestrator/config.js, orchestrator/executor.js, orchestrator/index.js, orchestrator/ingestor.js, orchestrator/util.js
=> feat: Changed  to process messages in parallel [release/v0.4.3]

orchestrator/nodes/http/index.js
=> Remove mandatory field when GET method

orchestrator/nodeManager.js
=> Add parameter to del remote node (to 0.5.0)

orchestrator/nodeManager.js
=> Add parameter to del remote node (to dev)

orchestrator/nodeManager.js, tests/docker-compose.yml
=> Add parameter to del remote node work (to 0.4.3)

orchestrator/nodes/http/index.js
=> Remove mandatory field on GET message

orchestrator/nodes/multi-actuate/locales/pt-BR.json, orchestrator/nodes/multi-device-out/locales/pt-BR.json
=> Fixes portuguese translation

orchestrator/nodes/multi-actuate/locales/pt-BR.json, orchestrator/nodes/multi-device-out/locales/pt-BR.json
=> Change portuguese translation

lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/package.json, lib/samples/kelvin/src/index.js
=> chore: upgrade libs examples [release/v0.4.3]

lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/package.json, lib/samples/kelvin/src/index.js
=> chore: upgrade libs examples [release/v0.5.0-alpha]

lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/package.json, lib/samples/kelvin/src/index.js
=> chore: upgrade libs examples [dev]

orchestrator/executor.js, orchestrator/nodes/http/index.js
dojot/dojot#1645
dojot/dojot#1650
=> fix: some undefined  variables in http node [dev] 

orchestrator/executor.js, orchestrator/nodes/http/index.js
dojot/dojot#1645
dojot/dojot#1650
=> fix: some undefined  variables in http node [v0.5.0]

orchestrator/nodes/actuate/actuate.html, orchestrator/nodes/multi-actuate/multi_actuate.html
=> Remove from list all devices when it's not have actuate attribute

orchestrator/nodes/kubernetesRemoteNode/index.js, orchestrator/package.json
=> Upgrage kubernetes-client

orchestrator/config.js, orchestrator/ingestor.js, orchestrator/package-lock.json, orchestrator/package.json, package-lock.json
=> [v0.5.0] Update dojot module

orchestrator/config.js, orchestrator/ingestor.js, orchestrator/package-lock.json, orchestrator/package.json, package-lock.json
=> [v0.4.4] Update dojot module

orchestrator/nodes/ftp/ftp.html
=> Add field to node ftp

orchestrator/nodes/actuate/actuate.html
=> Add filter to node actuate

orchestrator/dispatcher.js, orchestrator/nodeManager.js
=> Fix remove node [v0.5.0]

orchestrator/dispatcher.js, orchestrator/nodeManager.js
=> Fix remove node

orchestrator/dispatcher.js, orchestrator/nodeManager.js
=> Fix remove node [dev]

orchestrator/dispatcher.js, orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Fix problem when flowbroker and/or remote node are restarted [v0.4.4]

orchestrator/dispatcher.js, orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Fix problem when flowbroker and/or remote node are restarted [v0.5.0]

README.md
Changed the license badge in the Readme file.
NA
NA
No
No
=> Changed the license badge to Apache-2.0

lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/package.json
=> change license examples

orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Revert "Fix problem when flowbroker and/or remote node are restarted [dev]"

orchestrator/nodeManager.js, orchestrator/nodes/kubernetesRemoteNode/index.js
=> Revert "Revert "Fix problem when flowbroker and/or remote node are restarted [dev]""

lib/samples/arithmetic-mean/Dockerfile, lib/samples/arithmetic-mean/package-lock.json, lib/samples/arithmetic-mean/package.json, lib/samples/kelvin/Dockerfile, lib/samples/kelvin/package-lock.json, lib/samples/kelvin/package.json
dojot/dojot#1879
dojot/dojot#1930
=> Change lib version in examples

.github/workflows/main.yml, .gitignore, orchestrator/package-lock.json, orchestrator/package.json, tests/docker-compose.yml, tests/dojot-mock.js, tests/start-test.sh
=> changes to work with keycloak

orchestrator/nodes/switch/index.js, orchestrator/nodes/switch/switch.html
=> [Dev] [FlowBroker] Feat: Add in node "switch" the option to compare 2 values in 'msg'

orchestrator/nodes/http/index.js, orchestrator/nodes/template/index.js
Feature
Add possibility to send basic authentication in header HTTP Request
=> Add basic-authenticantion header

orchestrator/nodes/ftp/ftp.html, orchestrator/nodes/ftp/index.js
Bug fix
On node ftp request the file encoding is a text box
On node ftp request now the file encoding is a select box
dojot/dojot#2185
=> Change file encoding to option box

orchestrator/amqp.js, orchestrator/config.js
=> Reconnection to RabbitMQ

orchestrator/executor.js
[#dojot/2577](https://github.com/dojot/dojot/issues/2577) 
=> correction in instantiation order

orchestrator/config.js, orchestrator/nodeManager.js
https://dojot.atlassian.net/browse/DOJOT-95
=> [DOJOT-95] Update: actuation topic

orchestrator/executor.js
[#dojot/2577](https://github.com/dojot/dojot/issues/2577) 
=> promise return correction

orchestrator/index.js, orchestrator/ingestor.js, orchestrator/nodeManager.js, orchestrator/nodes/multi-actuate/multi_actuate.js
https://dojot.atlassian.net/browse/DOJOT-95
=> [DOJOT-95] The actuator topic split from data topic

orchestrator/DeviceCache.js, orchestrator/auth.js, orchestrator/ingestor.js
"fix getting tenant when service is restarted"
Bug fix
The images route asks for authentication
When the service restarts it fails to get the tenants
The images route no longer requires authentication
Tenant is being retrieved correctly
* No
[DOJOT-190](https://dojot.atlassian.net/browse/DOJOT-190)
* …
=> "image route does not need authentication"

.github/workflows/main.yml
=> test removed
